Vue.use(VueI18n)
const messages = {
    en: {
        text: {
            versionText: 'version: ',
            lastVersion: 'lastVersion',
            lang: 'lang',
            start: 'start',
            input: 'input',
            WebAPI: 'WebAPI',
            text: 'text',
            image: 'image',
            arithmetic: 'arithmetic',
            variableSetting: 'variableSetting',
            variableAgentSkillSettingNode: 'variableAgentSkillSettingNode',
            hanfei: 'hanfei',
            condition: 'condition',
            time: 'time',
            choice: 'choice',
            BackFlow: 'BackFlow',
            nextFlow: 'nextFlow',
            Customer: 'Customer',
            WaitRes: 'WaitRes',
            InterruptWait: 'InterruptWait',
            OpenWeb: 'OpenWeb',
            end: 'end',
            clear_canvas: 'clear canvas',
            parameter: 'parameter',
            saveNew: 'save new version',
            message_number: 'message number',
            cancel: 'cancel',
            save: 'save',
            description: 'description',
            save_alt: '',
            transferNode: '轉接',
        }
    },
    tw: {
        text: {
            hello: '哈囉',
            versionText: '版本號: ',
            lastVersion: '最新版',
            lang: '語系',
            start: '開始',
            input: '輸入',
            WebAPI: 'WebAPI',
            text: '文字',
            image: '圖文',
            arithmetic: '運算式',
            variableSetting: '一般變數設定',
            hanfei: '韓非',
            condition: '判斷式',
            variableAgentSkillSettingNode: '技能與群組變數設定',
            time: '日期比對',
            choice: '選單',
            BackFlow: '返回上一個對話流程',
            nextFlow: '轉跳其他對話流程',
            Customer: '客服',
            WaitRes: '等待回復',
            InterruptWait: '中斷並等待回復',
            OpenWeb: '開啟網站',
            end: '結束',
            clear_canvas: '清空畫布',
            parameter: '參數',
            saveNew: '存新版本',
            message_number: '訊息編號',
            cancel: '取消',
            save: '儲存',
            description: '描述',
            transferNode: '轉接',
        }
    },
    cn: {
        text: {
            versionText: '版本号: ',
            lastVersion: '最新版',
            lang: '语系',
            start: '开始',
            input: '输入',
            WebAPI: 'WebAPI',
            text: '文字',
            image: '图文',
            arithmetic: '运算式',
            variableSetting: '变数设定',
            variableAgentSkillSettingNode: '技能與群組變數設定',
            hanfei: '韩非',
            condition: '判断式',
            time: '日期比对',
            choice: '选单',
            BackFlow: '返回上一个对话流程',
            nextFlow: '转跳其他对话流程',
            Customer: '客服',
            WaitRes: '等待回复',
            InterruptWait: '中断并等待回复',
            OpenWeb: '开启网站',
            end: '结束',
            clear_canvas: '清空画布',
            parameter: '参数',
            saveNew: '存新版本',
            message_number: '讯息编号',
            cancel: '取消',
            save: '储存',
            description: '描述',
            transferNode: '轉接',
        }
    },
    jp: {
        text: {
            versionText: 'バージョン番号: ',
            lastVersion: '最新バージョン',
            lang: '言語ファミリー',
            start: '開始する',
            input: '入力',
            WebAPI: 'WebAPI',
            text: 'テキスト',
            image: '图文',
            arithmetic: '算術演算',
            variableSetting: '変数設定',
            variableAgentSkillSettingNode: '技能與群組變數設定',
            hanfei: 'ハンフェイ',
            condition: '判断',
            time: '日付の比較',
            choice: 'メニュー',
            BackFlow: '前の会話プロセスに戻る',
            nextFlow: '他の会話プロセスを有効にする',
            Customer: '顧客サービス',
            WaitRes: '返信待ち',
            InterruptWait: '割り込みして応答を待つ',
            OpenWeb: 'ウェブサイトを開く',
            end: '終了',
            clear_canvas: 'キャンバスを空にする',
            parameter: 'パラメータ',
            saveNew: '新しいバージョンを保存する',
            message_number: 'メッセージ番号',
            cancel: 'キャンセル',
            save: '保存',
            description: '説明',
            transferNode: '轉接',
        }
    }
}
const i18n = new VueI18n({
    locale: 'tw', // set locale
    fallbackLocale: 'tw',
    formatFallbackMessages: true,
    messages, // set locale dictionary

});

const app = new Vue({
    i18n
}).$mount('#wrap')
i18n.locale = lang;